input_folder: "input"
output_folder: "output"
max_memory: 1024
conversion_timeout: 30
log_level: "INFO"
max_connections_per_api: 3
max_threads: 4
batch_size: 1024
llm_api_key: "abcde123456"
llm_api_url: "www.example.com"
use_docintel: false
docintel_endpoint: "www.example2.com"
version: "1.0.0"
pool_refresh_rate: 60
pool_health_check_rate: 30