batch_size: 1024
conversion_timeout: 30
docintel_endpoint: http://www.example2.com
input_folder: input
llm_api_key: abcde123456
llm_api_url: http://www.example.com
log_level: INFO
max_connections_per_api: 3
max_memory: 1024
max_threads: 4
output_folder: output
pool_health_check_rate: 30
pool_refresh_rate: 60
print_configs_on_startup: true
use_docintel: false
version: 0.1.0
